### PR TITLE
Adding asset-pipeline support

### PR DESCRIPTION
**Pull request by davydotcom**
Adding support for asset-pipeline without removing resources plugin support, also added section in documentation for how to use.

### CODE REVIEW

**Comment by jfarcand** [comment]
Thanks!

**Comment by davydotcom** [comment]
Any idea when this might be released? Looking to replace atmosphere plugin fast.

**Comment by jfarcand** [comment]
@davydotcom What do you means by replace? @smaldini, maybe we could do a beta release?

**Comment by davydotcom** [comment]
Possibly yea, According to grails plugins this plugin hasnt been updated since january of 2013

**Pull request merged**
